### ISSUE TITLE
Publication Of Plug-Ins Without Dependencies

### ISSUE THREAD

**Issue by ilichenko** [inception-project/inception-plugin-server#12]
**Is your feature request related to a problem? Please describe.** 
As an INCEpTION-Plug-In-Developer, I need to be able to publish the plug-ins without dependencies that I have implemented on my PC to the Update-Server.

**Describe the solution you'd like** 

- [ ] The INCEpTION-Plug-In-Developer creates a jar file.
- [ ]  The INCEpTION-Plug-In-Developer uploads a jar file to the Update-Server. 
- [ ] The file is visible in the list of plug-ins and available to all users.

**Describe alternatives you've considered**
No alternatives considered.

**Comment by reckart** [comment]
I think whatever the solution coming out of #23 will be, we only need either #12 or #13.
