### ISSUE TITLE
Delete An Own Account

### ISSUE THREAD

**Issue by ilichenko** [inception-project/inception-plugin-server#4]
Description: As an INCEpTION-User or INCEpTION-Plug-In-Developer, I need to be able to delete my own account.

Acceptance Criterion: The INCEpTION-User and the INCEpTION-Plug-In- Developer have rights to delete their own accounts and cannot access their accounts after logging in. However, the plug-ins implemented and uploaded by the INCEpTION-Plug-In-Developer will continue to be available to the other INCEpTION-Users.

**Comment by reckart** [comment]
This is a duplicate it #3 - closing this one. All relevant requirements are documented in #3.
