### ISSUE TITLE
Successful Login

### ISSUE THREAD

**Issue by ilichenko** [inception-project/inception-plugin-server#5]
Description: As an INCEpTION-Plug-In-Developer or Update-Server-Administrator, I need to be able to authenticate myself to the Update-Server by username and password.

Acceptance Criterion: The dialog for logging in is displayed correctly. The users enter the valid data for logging in and get access to the account. The INCEpTION-Plug-In-Developer does not have administrator privileges.

**Comment by reckart** [comment]
This functionality is already provided by the base application template provided in #20.

We can consider the  INCEpTION-Plug-In-Developers to be users with the role `ROLE_USER` and Update-Server-Administrators to be users with the role `ROLE_ADMIN`. The other roles available in the template remain unused for the time being.
